### ISSUE TITLE
flipped bits in sniffed addresses

### ISSUE THREAD

**Issue by mothball187** [mothball187/flipperzero-nrf24#1]
occasionally, addresses sniffed with the nrfsniffer app will have its bits shifted once or twice and may have a bit or two flipped. in my testing, this happens sometimes with one of my tested devices. i'm not sure what is causing this, except to say that the technique used to sniff addresses is pretty hacky and not wholly reliable.

**Comment by UberGuidoZ** [comment]
From your own work... https://github.com/mothball187/flipperzero-nrf24/blob/main/nrfsniff/nrfsniff.c#L264 =)

**Comment by mothball187** [comment]
turns out, at least in my cases, the bits simply needed to be shifted by 1. a fix for this was implemented in https://github.com/mothball187/flipperzero-nrf24/commit/d8ccc4ee76185ab542ab09c4dc6c5f99c9df23a3. closing this issue for now.
