### ISSUE TITLE
2.4 ghz toys

### ISSUE THREAD

**Issue by Alfa16bravo** [mothball187/flipperzero-nrf24#16]
hello, is it possible to update app sniffing for remote control toys 2.4ghz ? thank you, and very good job

**Comment by mothball187** [comment]
@Alfa16bravo it may be possible, it depends on the toy's radio protocol. You would need to determine the preamble bits for the toy's radio protocol and then specify those in the code of the sniffing app. The technique used to enable sniffing with the nrf24 is not reliable, so there will be a lot of noise picked up. Additional filtering based on the protocol you are interested in would help with the noise.
