### ISSUE TITLE
GPIO connections

### ISSUE THREAD

**Issue by reidandrew91** [mothball187/flipperzero-nrf24#3]
Could you include a picture in the repo of the GPIO connections ?

**Comment by mothball187** [comment]
@reidandrew91 thanks for dropping by this repo! I am purposefully keeping the information on this repo to a minimum. Please see RogueMaster's firmware repo (includes these libs and apps) for the information you are seeking: https://github.com/RogueMaster/flipperzero-firmware-wPlugins/tree/unleashed/applications/mousejacker
