### ISSUE TITLE
nrf sniffer preamble AA / 55

### ISSUE THREAD

**Issue by Einstein2150** [mothball187/flipperzero-nrf24#9]
Hi. I'm again. Beside of my crazyradio pa I'm looking for the reason why nrf sniff isn't finding my Logitech device.

I found the preamble but doesn't understand what it does:

`nrf24_set_src_mac(nrf24_HANDLE, target_preamble, 2);`

Does the preamble sets the source-mac of the scanner or does it look for sniffed Mac starting with the preamble? In this case it wouldn't find my device because its not starting (or ending) with AA or 55 ...

**Comment by ESurge** [comment]
I think the preamble isn't used for Logitech devices. It's more for Jasco/GE devices which use 55 preamble, and other devices like Signia use AA preamble.

Preamble is in the packet data and not referencing the MAC address of the device.

For more information, check out:
https://www.bastille.net/research/vulnerabilities/mousejack/technical-details

**Comment by mothball187** [comment]
Please read http://travisgoodspeed.blogspot.com/2011/02/promiscuity-is-nrf24l01s-duty.html for an explanation of what the preamble is and how sniffing is done with the app.
